### ISSUE TITLE
App Idea: bleeverything --> will be used for future AWS/GCP tutorials

### ISSUE THREAD

**Issue by jaredfiacco2** [espruino/EspruinoApps#3]
Just a heads up:
I made a puck.js app that advertises sensor data over ble. 
I'm going to create a few tutorials in EspruinoDocs that use this app & EspruinoHub/NodeRed on a Raspberry Pi to send & store data on GCP & AWS. 
I'll add a PR for this app soon, work on the tutorial documentation for GCP/AWS, and then PR them into EspruinoDocs as well!
I've used this app at home on my puck.js & connected to AWS/GCP. I think other folks would have fun building them too! 

The App 
- Advertises acceleration detection/magnetic field/nfc field/button press states when a change occurs
- Advertises temperature, battery percentage, voltage, led states, and light sensor data once a minute while the button state remains 1

**Comment by gfwilliams** [comment]
Thanks! Just merged!

And referencing the tutorial at: https://github.com/espruino/EspruinoDocs/issues/666
